### ISSUE TITLE
THANK YOU - works on Dell 7440

### ISSUE THREAD

**Issue by iosonofabio** [stefanpartheym/archlinux-ipu6-webcam#29]
Mate, you saved my day, after days of searching around I finally got the camera to work by copy-pasting bits from your `install.sh`.

This works correctly on a Dell 7440 laptop, Alder lake 13th gen. Could you please add it to the README?

Should we make an Arch Wiki entry for this?

**Comment by alba4k** [comment]
I mentioned this on the XPS 9320 wiki (https://wiki.archlinux.org/title/Dell_XPS_13_Plus_(9320)#Webcam)

**Comment by alba4k** [comment]
There you go, opened a PR for you https://github.com/stefanpartheym/archlinux-ipu6-webcam/pull/30 :)

**Comment by stefanpartheym** [comment]
Thanks guys for the contributions!

**Comment by stefanpartheym** [comment]
Merged PR #30 – closing this one ;)
