### ISSUE TITLE
CapabilityBoundingSet should not be empty

### ISSUE THREAD

**Issue by fcapano** [stefanpartheym/archlinux-ipu6-webcam#71]
Testing on Wayland, on Arch Linux (EndeavourOS) 6.6.15-1-lts.

I've been having a hard time getting the webcam to work. It'd be fine in X11 but now Wayland, where all I'd see is a black screen in Firefox/Chrome/Cheese, and the v4l2-relayd service would crash.

I've narrowed it down to this line in the systemd service definition. Removing it makes it work again:
```
CapabilityBoundingSet=
```

Looking at [the docs](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#CapabilityBoundingSet=) and  `systemd-analyze capability`, I'm not sure which flags would need to be whitelisted, or if the flag is needed at all. 

I think a new sed entry in `v4l2-relayd/PKGBUILD` to remove that line is all that's needed to fix it.

**Comment by stefanpartheym** [comment]
Hi @fcapano,
thanks for filing the issue. It was the missing piece to make the camera work with PR #92 on Wayland running on a LTS kernel.
Fixed this in commit d1c471c.
