### ISSUE TITLE
Would this work on fedora?

### ISSUE THREAD

**Issue by varunkas** [stefanpartheym/archlinux-ipu6-webcam#73]
Hi, I’m a new Linux user and wanted to start with something noob friendly and installed Fedora on my DELL XPS 9315. I ended up here because (obviously) the webcam does not work. So, I have a couple of questions, for which I could not find answers. 

1. Will this install.sh script work for fedora? 
2.  If so, am I correct that I should use PKGMAN=(dnf)? 

Thanks so much!
Varun

**Comment by stefanpartheym** [comment]
Hi @varunkas,

the `install.sh` won't work on Fedora, that's for sure. I mean, technically, you could make it work on Fedora, if you would package each component in this repo for Fedora. However, this would require more advanced knowledge that's probably more specific to Fedora (as I'm not using Fedora, I couldn't do it either to be honest).

Currently, I fear, you have no choice other than trying to make it work yourself – sorry.

Will close this one, as this won't be done in this repo anytime soon, except someone submits a PR.

Best regards
Stefan
