### ISSUE TITLE
Is it possible to modify the resolution

### ISSUE THREAD

**Issue by elhossary** [stefanpartheym/archlinux-ipu6-webcam#75]
My Camera supports FHD resolution, but the default running resolution is 1280*720.

Is it possible to change some configuration to make "1920*1080" the default output resolution?

**Comment by stefanpartheym** [comment]
Hi @elhossary,

are you referring to general output resolution (i.e. resolution also in Chromium, Firefox, etc.)? Or are you referring to the output resolution from the test script?

**Comment by elhossary** [comment]
@stefanpartheym I see the resolution mentioned in the test script, can I make it permanent config for the cam output which Zoom for example will use

**Comment by stefanpartheym** [comment]
Hi @elhossary,
sorry to disappoint you, I have no clue, if that's possible. I guess, however, that it depends on the application accessing the camera. But as already mentioned, I have no clue, this is just a guess.
The only thing I can say for sure is, you can specify the output resolution in the test script, which will not influence the output resolution used in other applications.

**Comment by elhossary** [comment]
Okay, thanks
