### ISSUE TITLE
Dell XPS 13 plus (9320) on Manjaro 6.6.25-1: Success

### ISSUE THREAD

**Issue by melissawm** [stefanpartheym/archlinux-ipu6-webcam#78]
Hi all, 

`icamerasrc-git` does not build automatically on Manjaro 6.6.25-1. I get the following error:

```
gstcamerasrc.cpp: In function ‘gboolean gst_camerasrc_start(GstCamBaseSrc*)’:
gstcamerasrc.cpp:2839:27: error: too many arguments to function ‘int icamera::camera_device_open(int)’
 2839 |   ret = camera_device_open(camerasrc->device_id, camerasrc->num_vc);
      |         ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from gstcamerasrc.cpp:62:
/usr/include/libcamhal/api/ICamera.h:210:5: note: declared here
  210 | int camera_device_open(int camera_id);
      |     ^~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:624: libgsticamerasrc_la-gstcamerasrc.lo] Error 1
```

However, after checking out commit `931412a66cdf5d24ed77aa3b652a958dae9b2e9e` (as pointed by one of the comments at https://aur.archlinux.org/packages/icamerasrc-git) everything builds and the webcam works as expected.

Sharing in case other folks are looking for a solution and I'm happy to submit a PR if it helps. Cheers and thanks for putting this repo together!

**Comment by stefanpartheym** [comment]
Added the kernel to the README, thanks!
