### ISSUE TITLE
Reporting success on X1 Carbon Gen 11, 6.6.27-1-MANJARO

### ISSUE THREAD

**Issue by lukemarsden** [stefanpartheym/archlinux-ipu6-webcam#81]
Per my comment here: https://github.com/intel/ipu6-drivers/issues/187#issuecomment-2087967087

https://github.com/stefanpartheym/archlinux-ipu6-webcam/pull/80 + https://github.com/stefanpartheym/archlinux-ipu6-webcam/issues/71 + https://github.com/lukemarsden/ipu6-drivers/commit/473f5226586154cd4abf8553b7939551c34c56bd

This combination is working reliably on a machine that hitherto was highly flaky.

Suggest we aim to merge the above changes into main.

Reposting my comment from https://github.com/intel/ipu6-drivers/issues/187#issuecomment-2087967087

---

OK, wow, this issue is finally worked-around on my X1 Carbon Gen 11, and webcam is working reliably :tada: 

This is on Manjaro with kernel `6.6.27-1-MANJARO` for now, because it (a) has functional non-softisp setup, so picture quality is better and (b) is easier to patch kernel modules by pointing PKGBUILD files at forks of git repos

Instructions based on https://github.com/stefanpartheym/archlinux-ipu6-webcam:
* In case you had previous failed attempts from the repo, run `./uninstall.sh` and then reboot. Possibly run `paru -R intel-ipu6-dkms-git-fix intel-ipu6ep-camera-hal-git-fix icamerasrc-git-fix intel-ipu6ep-camera-bin-fix` if `./uninstall.sh` gives errors.
* Check out my fork at https://github.com/lukemarsden/archlinux-ipu6-webcam and switch to `fixes-for-recent-releases-77-79` branch - this contains the patch above in https://github.com/lukemarsden/ipu6-drivers/commit/473f5226586154cd4abf8553b7939551c34c56bd (pointed to in https://github.com/lukemarsden/archlinux-ipu6-webcam/commit/9f28e123eb95344ff6dc85973d953e3954908823), this is built on top of the code in https://github.com/stefanpartheym/archlinux-ipu6-webcam/pull/80
* Run `./install.sh -as`
* Apply the fix in https://github.com/stefanpartheym/archlinux-ipu6-webcam/issues/71
* Reboot _twice_
* `sudo gst-launch-1.0 icamerasrc ! autovideosink` now works 100% of the time on a machine where it used to work <30% of the time
* Webcam works reliably in Google Meet on Chrome

**Comment by stefanpartheym** [comment]
Added the kernel version to the README and referenced this issue.
Thank you :)
