### ISSUE TITLE
Works on Dell Latitude 7640

### ISSUE THREAD

**Issue by aleyoscar** [stefanpartheym/archlinux-ipu6-webcam#91]
Worked like a charm on my Dell Latitude 7640! Thank you so much for your work, it was super easy to install. Like others have said I was hunting around for a while for a solution and this solved it. Also on the latest lts kernel `6.6.48-1`.

OS: Arch Linux x86_64
Host: Latitude 7640
Kernel: 6.6.48-1-lts
CPU: 13th Gen Intel i7-1364U
GPU: Intel Raptor Lake-P [Iris Xe Graphics]

**Comment by stefanpartheym** [comment]
Hey @aleyoscar, thanks a lot! :)
I updated the README accordingly.
